# Generated by Django 3.2 on 2021-04-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUsers',
            fields=[
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coreusers')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
